# Sources make it possible to name and describe the data loaded
# into your warehouse by your extract and load tools

version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of the Postgres database used by our app
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        identifier: customers
        description: One record per customer.
        columns:
          - name: id
            data_type: number
          - name: first_name
            data_type: string
          - name: last_name
            data_type: string
      - name: orders
        identifier: orders
        description: One record per order. Includes cancelled and deleted orders.
        columns:
          - name: id
            data_type: number
          - name: user_id
            data_type: number
          - name: order_date
            data_type: date
          - name: status
            data_type: string
          - name: _etl_loaded_at
            data_type: timestamp
