# Sources make it possible to name and describe the data loaded
# into your warehouse by your extract and load tools

version: 2

sources:
  - name: stripe
    description: This is a replica of the Postgres database used by our app
    database: raw
    schema: stripe
    tables:
      - name: payment
        identifier: payment
        description: One record per customer.
        # we expected new data to be loaded into the
        # source table at least every 24 hours
        # _etl_loaded_at is a field that represents when new data is loaded
        loaded_at_field: _batched_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        columns:
          - name: order_id
            data_type: number
          - name: payment_method
            data_type: string
          - name: status
            data_type: string
          - name: amount
            data_type: number
          - name: created_at
            data_type: date
